### ISSUE TITLE
Creator3.4.0_2D_DrawingBoard   无法使用 保存都是黑屏

### ISSUE THREAD

**Issue by orzice** [cocos/cocos-awesome-tech-solutions#25]
Creator3.4.0_2D_DrawingBoard   无法使用 保存都是黑屏

**Comment by zhefengzhang** [comment]
收到， @yeshao2069 验证并修复一下。

**Comment by zhefengzhang** [comment]
请问你使用的哪个版本的引擎？

**Comment by orzice** [comment]
使用的就是3.4.0啊   平台是 mac 谷歌浏览器

**Comment by yeshao2069** [comment]
> 保存都是黑屏
- 请问 你是点击保存按钮吗？  可以看一下问题截图吗

**Comment by yeshao2069** [comment]
@orzice

**Comment by orzice** [comment]
哎  我之前保存 一直黑屏，我今天又试了试 居然正常了。很疑惑。

**Comment by orzice** [comment]
我大概知道为什么了  我一般调试都是F12 然后使用手机的UA  ，手机保存确实是黑屏的（手机：iphone 13）

**Comment by yeshao2069** [comment]
### OK

**Comment by yeshao2069** [comment]
重新设置  iPhone 里面的 webGL 和 Metal 设置。

设置 -> Safari浏览器 -> 高级 -> Experimental Features（试验性 WebKit 功能） 找到 
WebGL 2.0
WebGL via Metal
选项，关闭后重启，在浏览器上刷新即可。
