### ISSUE TITLE
spine局部换装3.6崩溃

### ISSUE THREAD

**Issue by zenskcode** [cocos/cocos-awesome-tech-solutions#41]
spine局部换装3.6社区版，原生崩溃
https://github.com/cocos/cocos-awesome-tech-solutions/tree/3.4.0-release/demo/Creator3.4.0_2D_spine_changeSlot_with_texture

**Comment by zhefengzhang** [comment]
你好，这是已知问题，后续在这个 issues 中跟进：https://github.com/cocos/cocos-engine/issues/12030
